version: '3.18'

services:

  postgres_db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  
  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"








